- documentation/private_key.md
- ext/rbsecp256k1/rbsecp256k1.c
Currently, we copy around the `Context` struct rather than just cloning the
`secp256k1_context` itself. This probably causes segmentation faults when
object lifetimes are not closely aligned with those of the `Context` object
that created them.
This change modifies this so that contexts are cloned onto objects that require
them for instance methods. This makesso context lifetimes safer (e.g. objects
using a context cannot outlive it).
> Copy Contexts Onto Objects

- ext/rbsecp256k1/extconf.rb
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/secp256k1_spec.rb
Add the struct, data type, and basic class definition for the new
`RecoverableSignature` type. Optionally include the recoverable signature code
if the appropriate header is available.
> Add RecoverableSignature Type

- .travis.yml
- Makefile
- documentation/context.md
- documentation/index.md
- documentation/recoverable_signature.md
- ext/rbsecp256k1/extconf.rb
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/rbsecp256k1/recoverable_signature_spec.rb
- spec/unit/secp256k1_spec.rb
Closes #5
Add support for recoverable signatures - signatures from which a public key
can be recovered. Add unit-tests corresponding to this and provide the
following new methods and classes:
* `Context#sign_recoverable`
* `Context#recoverable_signature_from_compact`
* `RecoverableSignature`
* `RecoverableSignature#compact`
* `RecoverableSignature#recover_public_key`
* `RecoverableSignature#to_signature`
> Add Recoverable Signature Support

- documentation/context.md
- documentation/private_key.md
- documentation/public_key.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/rbsecp256k1/private_key_spec.rb
- spec/unit/rbsecp256k1/public_key_spec.rb
Remove `PublicKey#initialize` and `PrivateKey#initialize`. Replace the previous
`PrivateKey#initialize` method with `Context#private_key_from_data`. We did not
add a substitute for `PublicKey#initialize` as it seems largely unnecessary at
this point.
> Replace PublicKey and PrivateKey initializers

- documentation/key_pair.md
- documentation/private_key.md
- documentation/public_key.md
- documentation/recoverable_signature.md
- documentation/signature.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/rbsecp256k1/signature_spec.rb
Closes #7.
Adds comparison operators to the following classes:
* `KeyPair`
* `PublicKey`
* `PrivateKey`
* `RecoverableSignature`
* `Signature`
> Add comparison operators

- .travis.yml
- Makefile
- README.md
- documentation/context.md
- documentation/index.md
- documentation/recoverable_signature.md
- documentation/shared_secret.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/secp256k1_spec.rb
Closes #8
Add support for the experimental EC Diffie-Hellman module (for those brave
enough to use it). This adds two new things:
* `Context#ecdh`
* `SharedSecret`
> Add Support For Experimental ECDH Module

- documentation/context.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/fuzzing/serialization_fuzzing_spec.rb
Add some fuzzing tests to look for crashes in the deserialization methods. Fuzz
tests are seeding using the same random seed RSpec is using. This makes them
reproducible.
> Add Fuzzing Tests

- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/context_spec.rb
* Add mising `String` type check in `key_pair_from_private_key`.
* Add `recovery_id` range check in `recoverable_signature_from_compact`.
* Add tests to ensure that inputs of the incorrec type are rejected.
* Add tests to ensure invalid recovery IDs are rejected.
> Add More Validations

- .rubocop.yml
- .travis.yml
- Makefile
- ext/rbsecp256k1/extconf.rb
- rbsecp256k1.gemspec
- spec/unit/secp256k1_spec.rb
Partially addresses #24. This makes the following changes:
* Default to download and building libsecp256k1 from GitHub zipfile.
* Add option `--with-system-library` to use system installed libsecp256k1 rather than download.
> Default To Downloading libsecp256k1

- ext/rbsecp256k1/extconf.rb
Add verification to ensure that the libsecp256k1 zipfile matches the zipfile
we expected. Download by git commit hash rather than download the tip of
master.
> Verify SHA256 Hash Of libsecp256k1 Zipfile

- .gitmodules
- Makefile
- README.md
We no longer need to vendor libsecp256k1 since we now download and compile it
as part of the compilation process.
> Remove Module vendor/secp256k1

- README.md
Explain why we chose to wrap libsecp256k1 in the README.
> Add Why Section To README

- Makefile
- ext/rbsecp256k1/extconf.rb
- rbsecp256k1.gemspec
If finding the openssl package fails, then automatically attempt to look in
the Homebrew SSL install path on macOS before failing.
> Automatically Infer Homebrew OpenSSL Path On MacOS

- documentation/context.md
- documentation/private_key.md
- documentation/public_key.md
- documentation/signature.md
- ext/rbsecp256k1/rbsecp256k1.c
- rbsecp256k1.gemspec
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/rbsecp256k1/private_key_spec.rb
- spec/unit/rbsecp256k1/public_key_spec.rb
Closes #41 by adding the following exception hierarchy under the Secp256k1
module:
```
Error < StandardError
├── SerializationError
├── DeserializationError
```
These exceptions are then used to replace most occurrences of `ArgumentError`
and `RuntimeError`. This will help packages using the library to isolate their
exception handling code to just those exceptions raised by the library itself.
> Add exception hierarchy

- .travis.yml
- Dockerfile
- Makefile
- README.md
Add the ability to run Valgrind's memcheck to check for memory leaks in when
running the test suite.
Adds the following three new make targets:
* `make docker` - creates a Docker image using the new Dockerfile.
* `make memcheck` - runs valgrind memcheck against the rspec test suite.
* `make memcheck-docker` - creates Docker container and runs memcheck within it.
These new make targets are used to create and run the valgrind tests as part
of the normal test suite.
> Add valgrind Memory Leak Checks

- ext/rbsecp256k1/extconf.rb
`rbspec256k1` is not running on m1 macs. We're seeing this error: https://github.com/etscrivner/rbsecp256k1/issues/54
I dug into the depedencies and noticed that the bitcoin-core/secp256k1 depedency has not been updated in 3 years. Using the latest `HEAD` fixed the issue on m1 macs and all tests are passing.
> Upgrade bitcoin-core/secp256k1 to latest HEAD

- .github/workflows/spec.yml
Fix the currently failing workflow builds due to `python-dev` apt dependency being replaced by `python`
> Fix: Workflows failing at python-dev dependency

- README.md
- documentation/releases/release-process.md
- ext/rbsecp256k1/extconf.rb
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/secp256k1_spec.rb
libsecp256k1 is now undergoing an officially release process with proper
stability and versioning. Upgrade rbsecp256k1 to use the official release
version. This involved:
* Changing the download URL in extconf.rb to the official release.
* Updating the SHA256 hash to that of the libsecp256k1-0.2.0.zip.
* Removing ECDH module enablement code as it is now enabled by default.
* Checking for additional headers.
* Changing secp256k1_context_no_precomp => secp256k1_context_static to fix
deprecation warning.
> Upgrade To Official Release libsecp256k1 v0.2.0

- README.md
- documentation/context.md
- documentation/shared_secret.md
- ext/rbsecp256k1/extconf.rb
- ext/rbsecp256k1/rbsecp256k1.c
The ECDH module is now on by default so clean up any documentation and code previously referencing that it required explicit enabling.
> Documentation and Code Cleanup For ECDH

- ext/rbsecp256k1/rbsecp256k1.c
- rbsecp256k1.gemspec
- spec/unit/rbsecp256k1/recoverable_signature_spec.rb
- Remove usage of `secp256k1_static_context` from `RecoverableSignature` as it has a context.
- Call `libsecp256k1_selftest` to validate the static context.
- Include all available libsecp256k1 headers
> Minimize Usage of Static Context

- documentation/index.md
- ext/rbsecp256k1/rbsecp256k1.c
Make PrivateKey#data a method instead of an attribute to prevent private key binary data from being printed in console sessions. Update the documentation appropriately.
Attempt to clear the private key secret memory on free for a small amount of added security.
> Make PrivateKey#data method instead of attribute

- documentation/public_key.md
- documentation/xonly_public_key.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/public_key_spec.rb
- spec/unit/rbsecp256k1/xonly_public_key_spec.rb
Part of the path to adding Schnorr signature support (#44).
Add a new class `XOnlyPublicKey` that represents a x-only pubkey. Include documentation for the new class. Add `PublicKey#to_xonly` to convert a `PublicKey` to an `XOnlyPublicKey`.
> Add Support For X-Only Public Keys

- documentation/key_pair.md
- ext/rbsecp256k1/rbsecp256k1.c
- spec/unit/rbsecp256k1/xonly_public_key_spec.rb
Part of #44 
Add a new convenience method, `KeyPair#xonly_public_key`, for easily retrieving the x-only public key from a `KeyPair`.
> Add KeyPair#xonly_public_key Method

- documentation/context.md
- documentation/index.md
- documentation/schnorr_signature.md
- documentation/secp256k1.md
- ext/rbsecp256k1/rbsecp256k1.c
- lib/rbsecp256k1/context.rb
- spec/unit/rbsecp256k1/context_spec.rb
- spec/unit/rbsecp256k1/schnorr_signature_spec.rb
- spec/unit/secp256k1_spec.rb
This completes the initial implementation of #44 
Add a new class called `SchnorrSignature` and new methods `Context#sign_schnorr` and `Context#sign_schnorr_custom` from producing these signatures. Add tests and update documentation.
> Add Schnorr Signature Support
